# Generated by Django 4.0.6 on 2022-07-26 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='管理员名称')),
                ('password', models.CharField(max_length=64, verbose_name='管理员密码')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='部门名称')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='名字')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (0, '女')], verbose_name='性别')),
                ('account', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='账户')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='入职时间')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.department', verbose_name='部门')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(choices=[(1, '普通'), (2, '紧急'), (3, '非常紧急')], default=1, verbose_name='紧急程度')),
                ('title', models.CharField(max_length=32, verbose_name='任务名称')),
                ('detail', models.TextField(verbose_name='任务详情')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.userinfo', verbose_name='用户')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('oid', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='订单编号')),
                ('title', models.CharField(max_length=32, verbose_name='订单名称')),
                ('price', models.FloatField(verbose_name='价格')),
                ('status', models.SmallIntegerField(choices=[(1, '未支付'), (2, '已支付'), (3, '已取消')], default=1, verbose_name='订单状态')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.admininfo', verbose_name='用户')),
            ],
        ),
    ]
