# Generated by Django 4.0.6 on 2022-07-28 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='城市名称')),
                ('count', models.IntegerField(verbose_name='城市人数')),
                ('img', models.FileField(upload_to='city', verbose_name='城市图片')),
            ],
        ),
    ]
