# Generated by Django 4.0.5 on 2022-06-30 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_department_userinfo_account_userinfo_create_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='create_time',
        ),
    ]
